version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_DOCKER://172.17.0.1:9092,PLAINTEXT_LOCAL://localhost:9091
      KAFKA_LISTENERS: PLAINTEXT_DOCKER://0.0.0.0:9092,PLAINTEXT_LOCAL://0.0.0.0:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "node-kafka-php"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  php:
    build: ./php
    volumes:
        - ./:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    links:
        - php
    volumes_from:
        - php
    ports:
      - 80:80
    networks:
      - mynetwork
networks:
  mynetwork:
