version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./docker/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "node-kafka-php"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  php:
    build: ./docker/php
    volumes:
        - ./:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www

  nginx:
    build: ./docker/nginx
    links:
        - php
    volumes_from:
        - php
    ports:
      - 80:80
